spring.application.name=logdemo
#logging.file.name=logs/app.log
#logging.pattern.file=%d{yyyy-mm-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#logging.pattern.console=%d{yyyy-mm-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#logging.level.root